host: 0.0.0.0
title: Kopako Services
email: Kopan.Dmytro@yahoo.com
description: >-
  Kubernetes Cluster On-Premises, Expertise for IT companies.
  I provide professional Kubernetes cluster installation services tailored for IT teams. 
baseurl: ""
url: "https://clusteronprem.eu"
twitter_username: dkopako
github_username:  kopako

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  quiet_deps: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
